CREATE TABLE "FILESERVER"."FILEREFRELATION"
(
"ID" BIGINT NOT NULL,
"GMT_CREATE" DATETIME(6),
"GMT_MODIFIED" DATETIME(6),
"STATUS" INT,
"FILEREF_ID" BIGINT NOT NULL,
"APP_ID" INT NOT NULL,
"REMARK" VARCHAR(255),
CLUSTER PRIMARY KEY("ID"),
UNIQUE("ID"),
CONSTRAINT "INDEX_FILE_APP" UNIQUE("FILEREF_ID", "APP_ID")) STORAGE(ON "YOUYUN", CLUSTERBTR) ;

