CREATE TABLE "FILESERVER"."YOZOFILEREF"
(
"ID" BIGINT NOT NULL,
"GMT_CREATE" DATETIME(6),
"GMT_MODIFIED" DATETIME(6),
"STATUS" INT,
"FILE_MD5" VARCHAR(100) NOT NULL,
"STORAGE_URL" VARCHAR(200) NOT NULL,
"FILE_SIZE" BIGINT,
"REMARK" VARCHAR(255),
CLUSTER PRIMARY KEY("ID"),
UNIQUE("ID"),
UNIQUE("FILE_MD5"),
UNIQUE("STORAGE_URL"));

