CREATE TABLE "PUBLIC"."yozofileref" (
	"ID" INT8 NOT NULL,
	"GMT_CREATE" TIMESTAMP(6) NULL,
	"GMT_MODIFIED" TIMESTAMP(6) NULL,
	"STATUS" INT4 NULL,
	"FILE_MD5" VARCHAR(100 char) NOT NULL,
	"STORAGE_URL" VARCHAR(200 char) NOT NULL,
	"FILE_SIZE" INT8 NULL,
	"REMARK" VARCHAR(255 char) NULL,
	CONSTRAINT "PUBLIC_yozofileref_CONSTRAINT_1" PRIMARY KEY ("ID")
)
WITH (
	OIDS=FALSE
);
CREATE UNIQUE INDEX "PUBLIC_yozofileref_INDEX_1" ON "PUBLIC"."yozofileref" (FILE_MD5);
CREATE UNIQUE INDEX "PUBLIC_yozofileref_INDEX_2" ON "PUBLIC"."yozofileref" (STORAGE_URL);

CREATE TABLE "PUBLIC"."filerefrelation" (
	"ID" INT8 NOT NULL,
	"GMT_CREATE" TIMESTAMP(6) NULL,
	"GMT_MODIFIED" TIMESTAMP(6) NULL,
	"STATUS" INT4 NULL,
	"FILEREF_ID" INT8 NOT NULL,
	"APP_ID" INT4 NOT NULL,
	"REMARK" VARCHAR(255 char) NULL,
	CONSTRAINT "PUBLIC_filerefrelation_CONSTRAINT_1" PRIMARY KEY ("ID")
)
WITH (
	OIDS=FALSE
);
CREATE UNIQUE INDEX "PUBLIC_filerefrelation_INDEX_1" ON "PUBLIC"."filerefrelation" (FILEREF_ID,APP_ID);





